### PR TITLE
add connect-port to projectConfig

### LINKED ISSUE #145: Make port configurable in projectConfig
I sometimes need to run two projects locally at the same time. Because biotope-build's serve process uses port 9000 by default, that's not possible without changing the used port. Currently it's possible to change it in biotope-build's `config.js` file. However, because that's a change in the node_modules folder, it gets lost upon every `yarn install` execution. 
My suggestion: make the port configurable in the `projectConfig.js` file like a lot of other features are.

### PR DESCRIPTION
**Pull request by luke-m**
fixes #145

### CODE REVIEW

**Comment by timomayer** [comment]
thank @luke-m 
why do you think the port should be in projectConfig? i prefr to have as less things as possible in projectConfig and if you need them in a project you can add them.

**Comment by luke-m** [comment]
Hmm well to me it wasn't obvious that it was even possible to do it. 
At first I found out you could change the port directly in `biotope-build`'s `config`. 
Then I found out that you could override that with the `projectConfig`. 
But this required me to look into how `build` works and uses the `config` etc. 
So to me it would've made it more obvious that it is possible at all, if such an entry would be in the `projectConfig` by default. 
I just checked the [documentation](https://boilerplate.biotope.sh/#/getting-started) for `projectConfig`, and there it doesn't explain that the whole content gets merged into `build`'s config. Here the wording suggests that only the things that are specified are configurable. 
So IMO we either need to add the port to the default `projectConfig` to make it obvious that it's configurable or we need to reword the documentation to reflect the fact that it's possible to override everything in the `build-config`.

**Comment by luke-m** [comment]
> i prefr to have as less things as possible in projectConfig and if you need them in a project you can add them

I don't necessarily share this point of view. IMO if the `projectConfig` is well documented, it helps the user a lot to understand what he/she can configure and what not. Or why do you think that there should me as little entries as possible?

**Comment by timomayer** [comment]
@luke-m i agree we have to improve the projectConfig documentation! if we have everything by default in the projectConfig and we change things with biotope-build updates it is a lot more things you have to manually update compared to if every project just has a few lines in the projectConfig which are really important for this project

**Comment by luke-m** [comment]
@timomayer check again please. I added a comment explaining the purpose of `projectConfig.js` and removed the connect-port.

**Pull request merged**
